FROM golang:1.25 AS builder
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /metric-producer ./cmd/metric-producer

FROM scratch
COPY --from=builder /metric-producer /metric-producer
ENTRYPOINT ["/metric-producer"]
